# ********************************************************************************
# FileName     : create-arduino-library-bundle.yml
# Description  : Create ETboard Arduino Library Bundle Package from public repository
# Author       : SCS
# Created Date : 2025.05.13
# Reference    : Based on existing copy-to-public-repository.yml workflow
# ********************************************************************************

name: Create ETboard Arduino Library Bundle

# 외부 저장소의 복사 작업 완료를 감지하기 위한 설정
on:
  repository_dispatch:
    types: [public-repo-updated]
  workflow_dispatch:  # 수동 트리거 옵션 유지

env:
 BUNDLE_DIR: "arduino_library_bundle_temp"
 EXTRACT_DIR: "arduino_library_extract_temp"
 OUTPUT_DIR: "resources/libs/arduino/all-zip"

jobs:
 create-bundle:
   # repository_dispatch 이벤트나 수동 실행시 동작
   if: ${{ github.event_name == 'repository_dispatch' || github.event_name == 'workflow_dispatch' }}
   runs-on: ubuntu-latest
   # 저장소 내용 수정을 위한 권한 추가
   permissions:
     contents: write
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4
       with:
         fetch-depth: 0  # 전체 히스토리 필요

     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.x'

     - name: Create Arduino Library Bundle
       run: |
         # 프로젝트 루트 디렉토리에서 실행
         python .github/scripts/etboard_library_utils.py full-process --debug

     - name: Upload bundle as artifact
       uses: actions/upload-artifact@v4
       with:
         name: arduino-library-bundle
         path: ${{ env.OUTPUT_DIR }}/*.zip
         if-no-files-found: error

     - name: Commit and push bundle
       run: |
         git config --global user.name 'GitHub Actions'
         git config --global user.email 'actions@github.com'
         git add ${{ env.OUTPUT_DIR }}/*.zip
         git commit -m "Update Arduino library bundle [skip ci]"
         git push

# ********************************************************************************
# End of File
# ********************************************************************************
